---
nextcloud:
  host: nextcloud.app.a14n.net
  configs:
    trusted_domains.config.php: |
      <?php
      $CONFIG = array (
        'trusted_domains' => array(
          0 => 'nextcloud',
          1 => 'nextcloud.app.a14n.net',
        ),
      );
