---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
    helm:
      parameters:
        - name: controller.extraArgs.enable-ssl-passthrough
          value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx-controller
