---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallabag-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: wallabag-ingress
    repoURL: https://github.com/adborden/gke-cloud.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
