---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nextcloud
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: wallabag
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: default
spec:
  sslPolicy: gke-1-modern  # configured manually via console
  redirectToHttps:
    enabled: true
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: default
spec:
  domains:
    - nextcloud.app.a14n.net
    - wallabag.app.a14n.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: default
    networking.gke.io/v1beta1.FrontendConfig: default
spec:
  rules:
    - host: nextcloud.app.a14n.net
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: nextcloud
              port:
                number: 8080
    - host: wallabag.app.a14n.net
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: wallabag
              port:
                number: 8080
