---
name: deploy
on:
  push:
    branches:
      - main

jobs:

  external-dns-app-cloud-1:
    name: external-dns (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/reusable-workflows
    with:
      app_name: external-dns
      app_namespace: external-dns
      cluster_name: app-cloud-1
      cluster_location: us-west1
      kustomize_overlay_name: app-cloud-1
    secrets: inherit

  external-dns-app-cloud-3:
    name: external-dns (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/reusable-workflows
    with:
      app_namespace: external-dns
      app_name: external-dns
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
      kustomize_overlay_name: app-cloud-3
    secrets: inherit

  default-ingress-app-cloud-1-production:
    name: default-ingress (production) (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/reusable-workflows
    with:
      app_namespace: production
      app_name: default-ingress
      cluster_name: app-cloud-1
      cluster_location: us-west1
    secrets: inherit

  nextcloud:
    name: nextcloud
    runs-on: ubuntu-latest
    environment: nextcloud
    env:
      app_namespace: production
      app_name: nextcloud
      cluster_name: app-cloud-1
      cluster_location: us-west1
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
      helm_additional_args: >-
        --set nextcloud.host=${{ secrets.NEXTCLOUD_HOST }}
        --set nextcloud.password=${{ secrets.NEXTCLOUD_PASSWORD }}
        --set postgresql.global.auth.password=${{ secrets.NEXTCLOUD_POSTGRESQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.cluster_name }}
          location: ${{ env.cluster_location }}
      - uses: azure/setup-helm@v3
        with:
           version: latest
      - name: helm repo add
        run: |
          helm repo add $helm_repository_name $helm_repository_url
      - id: diff
        name: helm diff
        run: |
          set +e
          template_yaml=$(mktemp)
          helm template $app_name $app_name/$helm_repository_name --namespace $app_namespace --values $app_name/values.yaml $helm_additional_args > $template_yaml
          if [[ $? -ne 0 ]]; then
            # helm failed, don't continue
            exit 1
          fi

          kubectl diff --namespace $app_namespace --filename $template_yaml > ${app_name}.diff
          if [[ $? -gt 1 ]]; then
            # an error occured, fail the job
            exit $?
          elif [[ $? == 1 && -s "${app_name}.diff" ]]; then
            # there's a diff, set an output for artifact upload.
            echo "::set-output name=artifact::${app_name}.diff"
          fi
      - if: ${{ steps.diff.outputs.artifact }}
        name: helm upgrade
        run: helm upgrade $app_name $app_name/$helm_repository_name --wait --install --namespace $app_namespace --values $app_name/values.yaml $helm_additional_args

  volumes:
    name: volumes (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/reusable-workflows
    with:
    env:
      app_name: volumes
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
    secrets: inherit
