---
name: deploy
on:
  push:
    branches:
      - main

jobs:
  external-dns:
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/resuable-workflows
    with:
      app_name: external-dns
      app_namespace: external-dns
    secrets: inherit

  default-ingress:
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/resuable-workflows
    with:
      app_name: default-ingress
      app_namespace: production
    secrets: inherit

  nextcloud:
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@feature/resuable-workflows
    environment: nextcloud
    with:
      app_name: nextcloud
      app_namespace: production
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
      #helm_additional_args: >-
      #  --set nextcloud.host=${{ secrets.NEXTCLOUD_HOST }}
      #  --set nextcloud.password=${{ secrets.NEXTCLOUD_PASSWORD }}
      #  --set postgresql.global.auth.password=${{ secrets.NEXTCLOUD_POSTGRESQL_PASSWORD }}
    secrets: inherit
