---
name: deploy
on:
  push:
    branches:
      - main

jobs:
  external-dns:
    name: external-dns
    runs-on: ubuntu-latest
    env:
      app_namespace: external-dns
      app_directory: external-dns
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: kube credentials
        run: gcloud container clusters get-credentials app-cloud-1 --region=us-west1
      - id: diff
        name: kubectl diff
        run: |
          set +e
          # kubectl diff exits 0 if there is no diff, 1 if there is a diff, >1 if error
          kubectl diff --namespace $app_namespace --filename $app_directory > ${app_directory}.diff
          if [[ $? -gt 1 ]]; then
            # an error occured, fail the job
            exit $?
          elif [[ $? == 1 ]]; then
            # there's a diff, set an output for artifact upload.
            echo "::set-output name=artifact::${app_directory}.diff"
          fi
      - if: ${{ steps.diff.outputs.artifact }}
        name: kubectl apply
        run: kubectl apply --namespace $app_namespace --filename $app_directory --wait

  default-ingress:
    name: default-ingress
    runs-on: ubuntu-latest
    env:
      app_namespace: production
      app_directory: default-ingress
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: kube credentials
        run: gcloud container clusters get-credentials app-cloud-1 --region=us-west1
      - id: diff
        name: kubectl diff
        run: |
          set +e
          # kubectl diff exits 0 if there is no diff, 1 if there is a diff, >1 if error
          kubectl diff --namespace $app_namespace --filename $app_directory > ${app_directory}.diff
          if [[ $? -gt 1 ]]; then
            # an error occured, fail the job
            exit $?
          elif [[ $? == 1 ]]; then
            # there's a diff, set an output for artifact upload.
            echo "::set-output name=artifact::${app_directory}.diff"
          fi
      - if: ${{ steps.diff.outputs.artifact }}
        name: kubectl apply
        run: kubectl apply --namespace $app_namespace --filename $app_directory --wait
