---
name: deploy helm
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_namespace:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      cluster_location:
        required: true
        type: string
      helm_repository_name:
        required: true
        type: string
      helm_repository_url:
        required: true
        type: string
      helm_additional_args:
        required: false
        type: string
    secrets:
      GCLOUD_SERVICE_ACCOUNT_KEY:
        required: true
      HELM_SECRET_VALUES:
        required: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    env:
      app_name: ${{ inputs.app_name }}
      app_namespace: ${{ inputs.app_namespace }}
      cluster_name: ${{ inputs.cluster_name}}
      cluster_location: ${{ inputs.cluster_location}}
      helm_repository_name: ${{ inputs.helm_repository_name }}
      helm_repository_url: ${{ inputs.helm_repository_url }}
      helm_additional_args: ${{ inputs.helm_additional_args }}
      HELM_SECRET_VALUES: ${{ secrets.HELM_SECRET_VALUES }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.cluster_name }}
          location: ${{ env.cluster_location }}
      - uses: azure/setup-helm@v3
        with:
           version: latest
      - name: helm repo add
        run: |
          helm repo add $helm_repository_name $helm_repository_url
      - id: diff
        name: helm diff
        run: |
          set +e
          template_yaml=$(mktemp)
          bin/helm_deploy.sh > $template_yaml
          if [[ $? -ne 0 ]]; then
            # helm failed, don't continue
            exit 1
          fi

          kubectl diff --namespace $app_namespace --filename $template_yaml > ${app_name}.diff
          kubectl_exit_code=$?
          if [[ "$kubectl_exit_code" -gt 1 ]]; then
            # an error occured, fail the job
            exit 1
          elif [[ "$kubectl_exit_code" == 1 && -s "${app_name}.diff" ]]; then
            # there's a diff, set an output for other jobs
            echo "::set-output name=diff::${app_name}.diff"
          fi
      - if: ${{ steps.diff.outputs.diff  && github.event_name == 'pull_request' }}
        name: post PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          # Pretty string to describe the app we're deploying.
          app_instance_description='${{ env.app_name }} (${{ env.app_namespace }}) (${{ env.cluster_name }})'

          cat <<EOF > pr_comment_body.txt
          <strong>${app_instance_description}</strong> is ready for deploy.

          <details>
          <summary>helm template diff <strong>${app_instance_description}</strong></summary>

          \`\`\`diff
          $(cat ${{ steps.diff.outputs.diff }})
          \`\`\`

          </details>

          - [ ] Please review the **${app_instance_description}** diff
          EOF

          gh pr comment ${{ github.event.number }} --body-file pr_comment_body.txt
      - if: ${{ steps.diff.outputs.diff && github.event_name == 'push' }}
        name: helm upgrade
        run: bin/helm_deploy.sh --commit
