---
name: deploy
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_namespace:
        required: true
        type: string
    secrets:
      GCLOUD_SERVICE_ACCOUNT_KEY:
        required: true

jobs:
  diff:
    name: kubectl diff ${{ inputs.app_name }} ${{ inputs.app_namespace }}
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    env:
      app_name: ${{ inputs.app_name }}
      app_namespace: ${{ inputs.app_namespace }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: kube credentials
        run: gcloud container clusters get-credentials app-cloud-1 --region=us-west1
      - id: diff
        name: kubectl diff
        run: |
          set +e
          # kubectl diff exits 0 if there is no diff, 1 if there is a diff, >1 if error
          kubectl diff --namespace $app_namespace --filename $app_name > ${app_name}.diff
          if [[ $? -gt 1 ]]; then
            # an error occured, fail the job
            exit $?
          elif [[ $? == 1 && -s "${app_name}.diff" ]]; then
            # there's a diff, set an output for reuse in other jobs
            echo "::set-output name=diff::${app_name}.diff"
          fi
      - if: ${{ steps.diff.outputs.diff  && github.event_name == 'pull_request' }}
        name: post comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          cat <<EOF > pr_comment_body.txt
          <strong>${{ env.app_directory }} (${{ env.app_namespace }})</strong> is ready for deploy.

          - [ ] Please review the **${{ env.app_directory }} (${{ env.app_namespace }})** diff

          <details>
          <summary>helm diff <strong>${{ env.app_directory }} (${{ env.app_namespace }})</strong></summary>

          \`\`\`diff
          $(cat ${{ steps.diff.outputs.diff }})
          \`\`\`

          </details>
          EOF

          gh pr comment ${{ github.event.number }} --body-file pr_comment_body.txt
      - if: ${{ steps.diff.outputs.diff && github.event_name == 'push' }}
        name: kubectl apply
        run: kubectl apply --namespace $app_namespace --filename $app_name --wait
