---
name: pull-request
on: [pull_request]

jobs:
  external-dns-app-cloud-1:
    name: external-dns (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: external-dns
      app_namespace: external-dns
      cluster_name: app-cloud-1
      cluster_location: us-west1
      kustomize_overlay_name: app-cloud-1
    secrets: inherit

  external-dns-app-cloud-3:
    name: external-dns (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: external-dns
      app_name: external-dns
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
      kustomize_overlay_name: app-cloud-3
    secrets: inherit

  default-ingress-app-cloud-1-production:
    name: default-ingress (app-cloud-1) (production)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: production
      app_name: default-ingress
      cluster_name: app-cloud-1
      cluster_location: us-west1
    secrets: inherit

  nextcloud:
    uses: adborden/gke-cloud/.github/workflows/helm-deploy-template.yml@main
    with:
      app_name: nextcloud
      app_namespace: production
      cluster_name: app-cloud-1
      cluster_location: us-west1
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
      helm_additional_args: >-
        --set nextcloud.host=nextcloud.app.a14n.net
    secrets: inherit

  volumes:
    name: volumes (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: volumes
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
    secrets: inherit
