---
name: pull-request
on: [pull_request]

jobs:
  external-dns-app-cloud-1:
    name: external-dns (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: external-dns
      app_namespace: external-dns
      cluster_name: app-cloud-1
      cluster_location: us-west1
      kustomize_overlay_name: app-cloud-1
    secrets: inherit

  external-dns-app-cloud-3:
    name: external-dns (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: external-dns
      app_name: external-dns
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
      kustomize_overlay_name: app-cloud-3
    secrets: inherit

  default-ingress-app-cloud-1-production:
    name: default-ingress (app-cloud-1) (production)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: production
      app_name: default-ingress
      cluster_name: app-cloud-1
      cluster_location: us-west1
    secrets: inherit

  nextcloud:
    name: nextcloud
    runs-on: ubuntu-latest
    environment: nextcloud
    env:
      app_namespace: production
      app_name: nextcloud
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
      helm_additional_args: >-
        --set nextcloud.host=${{ secrets.NEXTCLOUD_HOST }}
        --set nextcloud.password=${{ secrets.NEXTCLOUD_PASSWORD }}
        --set postgresql.global.auth.password=${{ secrets.NEXTCLOUD_POSTGRESQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v3
        with:
          version: latest
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}'
      - uses: 'google-github-actions/setup-gcloud@v0'
      - name: kube credentials
        run: gcloud container clusters get-credentials app-cloud-1 --region=us-west1
      - uses: azure/setup-helm@v3
        with:
           version: latest
      - name: helm repo add
        run: |
          helm repo add $helm_repository_name $helm_repository_url
      - id: diff
        name: helm diff
        run: |
          set +e
          template_yaml=$(mktemp)
          helm template $app_name $app_name/$helm_repository_name --namespace $app_namespace --values $app_name/values.yaml $helm_additional_args > $template_yaml
          if [[ $? -ne 0 ]]; then
            # helm failed, don't continue
            exit 1
          fi

          kubectl diff --namespace $app_namespace --filename $template_yaml > ${app_name}.diff
          if [[ $? -gt 1 ]]; then
            # an error occured, fail the job
            exit $?
          elif [[ $? == 1 && -s "${app_name}.diff" ]]; then
            # there's a diff, set an output for artifact upload.
            echo "::set-output name=artifact::${app_name}.diff"
          fi
      - if: ${{ steps.diff.outputs.artifact }}
        name: post comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          cat <<EOF > pr_comment_body.txt
          <strong>${{ env.app_name }} (${{ env.app_namespace }})</strong> is ready for deploy.

          <details>
          <summary>helm diff <strong>${{ env.app_name }} (${{ env.app_namespace }})</strong></summary>

          \`\`\`diff
          $(cat ${{ steps.diff.outputs.artifact }})
          \`\`\`

          </details>

          - [ ] Please review the **${{ env.app_name }} (${{ env.app_namespace }})** diff
          EOF

          gh pr comment ${{ github.event.number }} --body-file pr_comment_body.txt

  volumes:
    name: volumes (app-cloud-3)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: volumes
      cluster_name: app-cloud-3
      cluster_location: us-west1-a
    secrets: inherit
