---
name: pull-request
on: [pull_request]

jobs:
  external-dns-app-cloud-1:
    name: external-dns (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: external-dns
      app_namespace: external-dns
      cluster_name: app-cloud-1
      cluster_location: us-west1
      kustomize_overlay_name: app-cloud-1
    secrets: inherit

  external-dns-app-cloud-2:
    name: external-dns (app-cloud-2)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: external-dns
      app_name: external-dns
      cluster_name: app-cloud-2
      cluster_location: us-west1-a
      kustomize_overlay_name: app-cloud-2
    secrets: inherit

  default-ingress-app-cloud-1-production:
    name: default-ingress (production) (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_namespace: production
      app_name: default-ingress
      cluster_name: app-cloud-1
      cluster_location: us-west1
    secrets: inherit

  nextcloud-app-cloud-1-production:
    name: nextcloud (production) (app-cloud-1)
    uses: adborden/gke-cloud/.github/workflows/helm-deploy-template.yml@main
    with:
      app_name: nextcloud
      app_namespace: production
      cluster_name: app-cloud-1
      cluster_location: us-west1
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
    secrets: inherit

  nextcloud-app-cloud-2-stage:
    name: nextcloud (stage) (app-cloud-2)
    uses: adborden/gke-cloud/.github/workflows/helm-deploy-template.yml@main
    with:
      app_name: nextcloud
      app_namespace: stage
      cluster_name: app-cloud-2
      cluster_location: us-west1-a
      helm_repository_name: nextcloud
      helm_repository_url: https://nextcloud.github.io/helm/
    secrets: inherit

  volumes:
    name: volumes (app-cloud-2)
    uses: adborden/gke-cloud/.github/workflows/kubectl-deploy-template.yml@main
    with:
      app_name: volumes
      cluster_name: app-cloud-2
      cluster_location: us-west1-a
    secrets: inherit
